/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PosRouteImport } from './routes/pos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DealersRouteImport } from './routes/dealers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformRolesRouteImport } from './routes/platform.roles'
import { Route as PlatformPosRouteImport } from './routes/platform.pos'
import { Route as PlatformInventoryRouteImport } from './routes/platform.inventory'
import { Route as PlatformAnalyticsRouteImport } from './routes/platform.analytics'
import { Route as PlatformAiCenterRouteImport } from './routes/platform.ai-center'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersRoute = DealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRolesRoute = PlatformRolesRouteImport.update({
  id: '/platform/roles',
  path: '/platform/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPosRoute = PlatformPosRouteImport.update({
  id: '/platform/pos',
  path: '/platform/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformInventoryRoute = PlatformInventoryRouteImport.update({
  id: '/platform/inventory',
  path: '/platform/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAnalyticsRoute = PlatformAnalyticsRouteImport.update({
  id: '/platform/analytics',
  path: '/platform/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAiCenterRoute = PlatformAiCenterRouteImport.update({
  id: '/platform/ai-center',
  path: '/platform/ai-center',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/dealers': typeof DealersRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/platform/ai-center': typeof PlatformAiCenterRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/inventory': typeof PlatformInventoryRoute
  '/platform/pos': typeof PlatformPosRoute
  '/platform/roles': typeof PlatformRolesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/dealers': typeof DealersRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/platform/ai-center': typeof PlatformAiCenterRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/inventory': typeof PlatformInventoryRoute
  '/platform/pos': typeof PlatformPosRoute
  '/platform/roles': typeof PlatformRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/dealers': typeof DealersRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/platform/ai-center': typeof PlatformAiCenterRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/inventory': typeof PlatformInventoryRoute
  '/platform/pos': typeof PlatformPosRoute
  '/platform/roles': typeof PlatformRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invitation'
    | '/ai'
    | '/analytics'
    | '/contact'
    | '/customers'
    | '/dashboard'
    | '/dealers'
    | '/inventory'
    | '/login'
    | '/onboarding'
    | '/pos'
    | '/pricing'
    | '/register'
    | '/security'
    | '/settings'
    | '/stores'
    | '/platform/ai-center'
    | '/platform/analytics'
    | '/platform/inventory'
    | '/platform/pos'
    | '/platform/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-invitation'
    | '/ai'
    | '/analytics'
    | '/contact'
    | '/customers'
    | '/dashboard'
    | '/dealers'
    | '/inventory'
    | '/login'
    | '/onboarding'
    | '/pos'
    | '/pricing'
    | '/register'
    | '/security'
    | '/settings'
    | '/stores'
    | '/platform/ai-center'
    | '/platform/analytics'
    | '/platform/inventory'
    | '/platform/pos'
    | '/platform/roles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accept-invitation'
    | '/ai'
    | '/analytics'
    | '/contact'
    | '/customers'
    | '/dashboard'
    | '/dealers'
    | '/inventory'
    | '/login'
    | '/onboarding'
    | '/pos'
    | '/pricing'
    | '/register'
    | '/security'
    | '/settings'
    | '/stores'
    | '/platform/ai-center'
    | '/platform/analytics'
    | '/platform/inventory'
    | '/platform/pos'
    | '/platform/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContactRoute: typeof ContactRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DealersRoute: typeof DealersRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PosRoute: typeof PosRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  StoresRoute: typeof StoresRoute
  PlatformAiCenterRoute: typeof PlatformAiCenterRoute
  PlatformAnalyticsRoute: typeof PlatformAnalyticsRoute
  PlatformInventoryRoute: typeof PlatformInventoryRoute
  PlatformPosRoute: typeof PlatformPosRoute
  PlatformRolesRoute: typeof PlatformRolesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers': {
      id: '/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof DealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/roles': {
      id: '/platform/roles'
      path: '/platform/roles'
      fullPath: '/platform/roles'
      preLoaderRoute: typeof PlatformRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/pos': {
      id: '/platform/pos'
      path: '/platform/pos'
      fullPath: '/platform/pos'
      preLoaderRoute: typeof PlatformPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/inventory': {
      id: '/platform/inventory'
      path: '/platform/inventory'
      fullPath: '/platform/inventory'
      preLoaderRoute: typeof PlatformInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/analytics': {
      id: '/platform/analytics'
      path: '/platform/analytics'
      fullPath: '/platform/analytics'
      preLoaderRoute: typeof PlatformAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/ai-center': {
      id: '/platform/ai-center'
      path: '/platform/ai-center'
      fullPath: '/platform/ai-center'
      preLoaderRoute: typeof PlatformAiCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContactRoute: ContactRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DealersRoute: DealersRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PosRoute: PosRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  StoresRoute: StoresRoute,
  PlatformAiCenterRoute: PlatformAiCenterRoute,
  PlatformAnalyticsRoute: PlatformAnalyticsRoute,
  PlatformInventoryRoute: PlatformInventoryRoute,
  PlatformPosRoute: PlatformPosRoute,
  PlatformRolesRoute: PlatformRolesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
